### ISSUE TITLE
Cannot run network client code

### ISSUE THREAD

**Issue by abailly** [snoyberg/haskell-scratch#2]
Hello,
I am trying to use your technique to package a minimal container for my application but I run into an issue: application uses wreq as a client to connect to various services and when running in a minimal container, I got the following error:

```
getProtocolByName: does not exist (no such protocol name: tcp)
```

This looks very similar to https://github.com/bos/wreq/issues/5 : Some file is probably missing, however I added the missing `/etc/protocols` and `/etc/services` files from `netbase` package which apparently could be causing that issue. And I am still encountering same problem.

Any clues?

**Comment by snoyberg** [comment]
I actually ran into that exact issue myself, and don't know what caused it. I'll ping someone at work who may know something about this.

**Comment by abailly** [comment]
Great, thanks! I will keep on trying to solve it too...

**Comment by abailly** [comment]
FWIW, Here is the list of opened files (removing not found) when it successfully connects to the outside world:

```
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
open("/lib/x86_64-linux-gnu/librt.so.1", O_RDONLY|O_CLOEXEC) = 3
open("/lib/x86_64-linux-gnu/libdl.so.2", O_RDONLY|O_CLOEXEC) = 3
open("/lib/x86_64-linux-gnu/libpthread.so.0", O_RDONLY|O_CLOEXEC) = 3
open("/usr/lib/x86_64-linux-gnu/libgmp.so.10", O_RDONLY|O_CLOEXEC) = 3
open("/lib/x86_64-linux-gnu/libm.so.6", O_RDONLY|O_CLOEXEC) = 3
open("/lib/x86_64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
open("/usr/lib/locale/locale-archive", O_RDONLY|O_CLOEXEC) = 3
open("/proc/meminfo", O_RDONLY|O_CLOEXEC) = 3
open("events.dat", O_RDWR|O_CREAT|O_NOCTTY|O_NONBLOCK, 0666) = 11
open(".server.key", O_RDONLY|O_NOCTTY|O_NONBLOCK) = 12
open("/etc/nsswitch.conf", O_RDONLY|O_CLOEXEC) = 13
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 13
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 13
open("/lib/x86_64-linux-gnu/libnss_files.so.2", O_RDONLY|O_CLOEXEC) = 13
open("/etc/protocols", O_RDONLY|O_CLOEXEC) = 13
open("/etc/host.conf", O_RDONLY|O_CLOEXEC) = 14
open("/etc/resolv.conf", O_RDONLY|O_CLOEXEC) = 14
open("/etc/hosts", O_RDONLY|O_CLOEXEC)  = 14
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 14
open("/lib/x86_64-linux-gnu/libnss_dns.so.2", O_RDONLY|O_CLOEXEC) = 14
open("/lib/x86_64-linux-gnu/libresolv.so.2", O_RDONLY|O_CLOEXEC) = 14
open("/etc/resolv.conf", O_RDONLY|O_CLOEXEC) = 14
open("/dev/random", O_RDONLY|O_NONBLOCK) = 15
open("/dev/urandom", O_RDONLY|O_NONBLOCK) = 15
open("/dev/random", O_RDONLY|O_NONBLOCK) = 15
open("/dev/urandom", O_RDONLY|O_NONBLOCK) = 15
```

Looks like some of those files are missing in your manifest, I will try to copy them and see how it goes.

**Comment by abailly** [comment]
OK, apparently adding all `libnss_XXX` files solves my issue: Application can connect to outside world.

**Comment by snoyberg** [comment]
That's cool. How much extra space does that take in the image? If it's not significant, would you send a PR to include them?

**Comment by abailly** [comment]
```
-rwxr-xr-x    1 root     root       1840928 Jun 16 13:32 libc.so.6
-rw-r--r--    1 root     root         14664 Jun 16 13:32 libdl.so.2
-rw-r--r--    1 root     root       1071552 Jun 16 13:32 libm.so.6
-rw-r--r--    1 root     root         22952 Jun 16 13:32 libnss_dns.so.2
-rw-r--r--    1 root     root         47712 Jun 16 13:32 libnss_files.so.2
-rwxr-xr-x    1 root     root        141574 Jun 16 13:32 libpthread.so.0
-rw-r--r--    1 root     root        101240 Jun 16 13:32 libresolv.so.2
-rw-r--r--    1 root     root         31792 Jun 16 13:32 librt.so.1
-rw-r--r--    1 root     root         10680 Jun 16 13:32 libutil.so.1
-rw-r--r--    1 root     root        100728 Jun 16 13:32 libz.so.1
```

Does not seem too much to me: ~170KB.

 WDYT?

**Comment by snoyberg** [comment]
LGTM, thanks!

**Comment by dysinger** [comment]
@abailly @snoyberg I had to add a complete libc & ca-certificates from ubuntu to make outbound https work.

**Comment by abailly** [comment]
I ran into another issue: The `/etc/hosts` file in the container is empty when it starts: http://stackoverflow.com/questions/30874184/why-is-etc-hosts-file-empty-in-my-docker-container

**Comment by AlexeyRaga** [comment]
@dysinger do you have an example of how you managed to make it find the certificates?

**Comment by robertmassaioli** [comment]
I got this same error in one of my Docker images that was attempting to run a Snap app inside of a Ubuntu 16.04 image. Installing these packages in the image fixed the issue:

    libnss3 libnss-lwres libnss-mdns

Thanks for the tip in the right direction! (Note: I don't know if all three are required but the issue is now resolved)

**Comment by dmjio** [comment]
```
getProtocolByName: does not exist (no such protocol name: tcp)
```

Is still happening to me when accessing hackage over `http` concurrently.

Can we reopen?
